/* @flow */

/** Proposal Action */
export const PROPOSE_SUCCESS = 'PROPOSAL_PROPOSE_SUCCESS';
export const PROPOSAL_LOAD = 'PROPOSAL_LOAD';
/** Register Action */
export const REGISTER_REQUEST = 'USER_REGISTER_REQUEST';
export const REGISTER_SUCCESS = 'USER_REGISTER_SUCCESS';
export const REGISTER_FAILURE = 'USER_REGISTER_FAILURE';
/** Login Action */
export const LOGIN_REQUEST = 'USER_LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'USER_LOGIN_FAILURE';
export const GET_INFO = 'USER_GET_INFO';
export const GET_TOKEN = 'USER_GET_TOKEN';
export const LOGIN_SOCIAL_REQUEST = 'USER_LOGIN_SOCIAL_REQUEST';
export const LOGIN_SOCIAL_SUCCESS = 'USER_LOGIN_SOCIAL_SUCCESS';
export const LOGIN_SOCIAL_FAILURE = 'USER_LOGIN_SOCIAL_FAILURE';
export const LOGOUT = 'USER_LOGOUT';
/** Forgot Password Action */
export const FORGOT_PASSWORD_REQUEST = 'USER_FORGOT_PASSWORD_REQUEST';
export const FORGOT_PASSWORD_SUCCESS = 'USER_FORGOT_PASSWORD_SUCCESS';
export const FORGOT_PASSWORD_FAILURE = 'USER_FORGOT_PASSWORD_FAILURE';
export const FORGOT_PASSWORD_INIT = 'USER_FORGOT_PASSWORD_INIT';
/** Pannel action */
export const PANNEL_CLOSE = 'PANNEL_CLOSE';
export const PANNEL_SHOW_LOGIN = 'PANNEL_SHOW_LOGIN';
export const PANNEL_SHOW_REGISTER = 'PANNEL_SHOW_REGISTER';
export const PANNEL_SHOW_FORGOT_PASSWORD = 'PANNEL_SHOW_FORGOT_PASSWORD';
/** Modal action */
export const MODAL_CLOSE = 'MODAL_CLOSE';
export const MODAL_SHOW_LOGIN = 'MODAL_SHOW_LOGIN';
export const MODAL_SHOW_REGISTER = 'MODAL_SHOW_REGISTER';
export const MODAL_SHOW_FORGOT_PASSWORD = 'MODAL_SHOW_FORGOT_PASSWORD';
export const MODAL_SHOW_DEPARTMENT_FORM = 'MODAL_SHOW_DEPARTMENT_FORM';
export const MODAL_SHOW_SESSION_EXPIRATION = 'MODAL_SHOW_SESSION_EXPIRATION';
export const MODAL_CLOSE_SESSION_EXPIRATION = 'MODAL_CLOSE_SESSION_EXPIRATION';
/** Sequence action */
export const SEQUENCE_COLLAPSE = 'SEQUENCE_COLLAPSE';
export const QUESTION_LOAD = 'QUESTION_LOAD';
export const QUESTION_UNLOAD = 'QUESTION_UNLOAD';
export const QUESTION_RESULTS_LOAD = 'QUESTION_RESULTS_LOAD';
export const QUESTION_POPULAR_TAGS_LOAD = 'QUESTION_POPULAR_TAGS_LOAD';
export const CURRENT_QUESTION_UPDATE = 'CURRENT_QUESTION_UPDATE';
export const SEQUENCE_PROPOSAL_VOTE = 'SEQUENCE_PROPOSAL_VOTE';
export const SEQUENCE_PROPOSAL_UNVOTE = 'SEQUENCE_PROPOSAL_UNVOTE';
/** Notification action */
export const NOTIFICATION_CLOSE = 'NOTIFICATION_CLOSE';
export const NOTIFICATION_LOGIN_SUCCESS = 'NOTIFICATION_LOGIN_SUCCESS';
export const NOTIFICATION_LOGOUT_SUCCESS = 'NOTIFICATION_LOGOUT_SUCCESS';
export const NOTIFICATION_REGISTER_SUCCESS = 'NOTIFICATION_REGISTER_SUCCESS';
export const NOTIFICATION_ACCOUNT_DELETION_SUCCESS =
  'NOTIFICATION_ACCOUNT_DELETION_SUCCESS';
export const NOTIFICATION_SECURE_EXPIRED = 'NOTIFICATION_SECURE_EXPIRED';
/** Password Recovery */
export const PASSWORD_RECOVERY_REQUEST = 'USER_PASSWORD_RECOVERY_REQUEST';
export const PASSWORD_RECOVERY_FAILURE = 'USER_PASSWORD_RECOVERY_FAILURE';
export const PASSWORD_RECOVERY_SUCCESS = 'USER_PASSWORD_RECOVERY_SUCCESS';
/** Custom data */
export const CUSTOM_DATA_SET_KEY = 'CUSTOM_DATA_SET_KEY';
export const CUSTOM_DATA_REMOVE_KEY = 'CUSTOM_DATA_REMOVE_KEY';
