export const homepageTypeFixture = {
  highlights: {
    participantsCount: 1808,
    proposalsCount: 3107,
    partnersCount: 115,
  },
  currentQuestions: [
    {
      questionId: '66a9230b-08cb-4f37-8ed8-aa95a8eac19a',
      questionSlug: 'environnement',
      question: "Comment agir ensemble dès maintenant pour l'environnement ?",
      shortTitle: null,
      operationTitle: "Agir ensemble pour l'environnement",
      consultationImage:
        'https://assets.preprod.makeorg.tech/assets/content/operations/environnement/a084deb8-c314-4735-a1d1-038f92d91af8.png',
      descriptionImage:
        'https://assets.preprod.makeorg.tech/assets/content/operations/environnement/0865fee3-e88a-450e-9bf6-2c228689be9c.jpg',
      country: 'FR',
      language: 'fr',
      startDate: '2019-10-16T22:00:00Z',
      endDate: '2020-07-30T22:00:00Z',
      theme: {
        gradientStart: '#a4d693',
        gradientEnd: '#007d83',
        color: '#007d83',
        fontColor: '#e5ef5a',
        secondaryColor: '#000000',
        secondaryFontColor: '#ffffff',
      },
      displayResults: true,
      resultsLink: {
        kind: 'internal',
        value: 'top-ideas',
      },
      aboutUrl: 'https://about.make.org/about-environnement',
      actions: '',
      featured: true,
      participantsCount: 902,
      proposalsCount: 163,
    },
  ],
  featuredQuestions: [
    {
      questionId: '66a9230b-08cb-4f37-8ed8-aa95a8eac19a',
      questionSlug: 'environnement',
      question: "Comment agir ensemble dès maintenant pour l'environnement ?",
      shortTitle: null,
      operationTitle: "Agir ensemble pour l'environnement",
      consultationImage:
        'https://assets.preprod.makeorg.tech/assets/content/operations/environnement/a084deb8-c314-4735-a1d1-038f92d91af8.png',
      descriptionImage:
        'https://assets.preprod.makeorg.tech/assets/content/operations/environnement/0865fee3-e88a-450e-9bf6-2c228689be9c.jpg',
      country: 'FR',
      language: 'fr',
      startDate: '2019-10-16T22:00:00Z',
      endDate: '2020-07-30T22:00:00Z',
      theme: {
        gradientStart: '#a4d693',
        gradientEnd: '#007d83',
        color: '#007d83',
        fontColor: '#e5ef5a',
        secondaryColor: '#000000',
        secondaryFontColor: '#ffffff',
      },
      displayResults: true,
      resultsLink: {
        kind: 'internal',
        value: 'top-ideas',
      },
      aboutUrl: 'https://about.make.org/about-environnement',
      actions: '',
      featured: true,
      participantsCount: 902,
      proposalsCount: 163,
    },
    {
      questionId: '7b23ef97-d52a-4cca-98aa-d4be75056ccf',
      questionSlug: 'bretagne-ecologique-durable',
      question: 'Comment mieux protéger l’environnement en Bretagne ?',
      shortTitle: 'Environnement',
      operationTitle:
        'Comment faire de la Bretagne une région plus écologique et durable ?',
      consultationImage:
        'https://assets.preprod.makeorg.tech/assets/content/operations/region-bretagne/cff488a7-a58f-40b5-8224-661b4242e32d.jpg',
      descriptionImage:
        'https://assets.preprod.makeorg.tech/assets/content/operations/region-bretagne/df9e0bb6-018d-4609-8bf6-f47550808ff3.jpg',
      country: 'FR',
      language: 'fr',
      startDate: '2019-10-12T22:00:00Z',
      endDate: '2020-07-18T22:00:00Z',
      theme: {
        gradientStart: '#21816e',
        gradientEnd: '#21816e',
        color: '#21816e',
        fontColor: '#FFFFFF',
        secondaryColor: null,
        secondaryFontColor: null,
      },
      displayResults: true,
      resultsLink: {
        kind: 'internal',
        value: 'results',
      },
      aboutUrl: null,
      actions: null,
      featured: true,
      participantsCount: 0,
      proposalsCount: 0,
    },
    {
      questionId: '7108965b-0229-4e00-b313-abb491dee6ac',
      questionSlug: 'culture',
      question: 'Comment rendre la culture accessible à tous?',
      shortTitle: null,
      operationTitle: 'test culture',
      consultationImage:
        'https://assets.preprod.makeorg.tech/assets/content/operations/culture/e2a2f76c-ec0f-4a7c-80d5-a60eb52acf95.svg',
      descriptionImage:
        'https://assets.preprod.makeorg.tech/assets/content/operations/culture/4b1a8c7e-7cfb-40f3-96fa-ac7e6290a264.JPG',
      country: 'FR',
      language: 'fr',
      startDate: '2018-06-27T00:00:00Z',
      endDate: '2020-07-14T00:00:00Z',
      theme: {
        gradientStart: '#000000',
        gradientEnd: '#000000',
        color: '#000000',
        fontColor: '#FFFFFF',
        secondaryColor: null,
        secondaryFontColor: null,
      },
      displayResults: false,
      resultsLink: null,
      aboutUrl: 'https://about.make.org/about-culture',
      actions: null,
      featured: true,
      participantsCount: 0,
      proposalsCount: 0,
    },
    {
      questionId: '3548602e-7592-4ecc-9825-6ce80870cab9',
      questionSlug: 'chance-aux-jeunes',
      question: 'Comment donner une chance à chaque jeune ???',
      shortTitle: null,
      operationTitle: 'Comment donner une chance à chaque jeune ?',
      consultationImage:
        'https://assets.preprod.makeorg.tech/assets/avatars/1ebacbca-8c19-4cbd-a809-6c322ed93c38/4c0a6dfb-a509-4173-9a70-aee59b8bf5c6.jpg',
      descriptionImage:
        'https://assets.preprod.makeorg.tech/assets/content/operations/chance-aux-jeunes/4784f632-33a0-4c9e-82c3-fb8b73b2db8d.png',
      country: 'FR',
      language: 'fr',
      startDate: '2018-08-29T18:00:00Z',
      endDate: '2020-07-05T14:00:00Z',
      theme: {
        gradientStart: '#000000',
        gradientEnd: '#000000',
        color: '#000000',
        fontColor: '#FFFFFF',
        secondaryColor: null,
        secondaryFontColor: null,
      },
      displayResults: false,
      resultsLink: null,
      aboutUrl: null,
      actions: null,
      featured: true,
      participantsCount: 3,
      proposalsCount: 1618,
    },
    {
      questionId: 'efd59e93-64a2-4e6f-8dcb-c87a879cabf8',
      questionSlug: 'place-handicap',
      question: 'Comment donner une vraie place aux personnes handicapées ?',
      shortTitle: null,
      operationTitle: 'Handicap',
      consultationImage: null,
      descriptionImage: null,
      country: 'FR',
      language: 'fr',
      startDate: '2019-04-06T00:00:00Z',
      endDate: '2020-06-26T00:00:00Z',
      theme: {
        gradientStart: '#000000',
        gradientEnd: '#000000',
        color: '#000000',
        fontColor: '#07e0d0',
        secondaryColor: null,
        secondaryFontColor: null,
      },
      displayResults: false,
      resultsLink: null,
      aboutUrl: 'https://about.make.org/about-handicap',
      actions: null,
      featured: true,
      participantsCount: 0,
      proposalsCount: 0,
    },
    {
      questionId: '0054db0a-9ae0-402b-9189-b88c457d501e',
      questionSlug: 'aines',
      question: 'Comment mieux prendre soin de nos aînés ?',
      shortTitle: null,
      operationTitle: 'Comment mieux prendre soin de nos aînés ?',
      consultationImage:
        'https://assets.preprod.makeorg.tech/assets/content/operations/aines/f699ef46-c3f5-4a1b-ab0c-9ec49d127a11.png',
      descriptionImage:
        'https://assets.preprod.makeorg.tech/assets/content/operations/aines/cc73df1a-efd6-472c-a192-bf458fb618dc.jpg',
      country: 'FR',
      language: 'fr',
      startDate: '2019-01-23T00:00:00Z',
      endDate: '2020-06-11T00:00:00Z',
      theme: {
        gradientStart: '#9C6BDA',
        gradientEnd: '#8DDCF6',
        color: '#9C6BDA',
        fontColor: '#000000',
        secondaryColor: null,
        secondaryFontColor: null,
      },
      displayResults: true,
      resultsLink: {
        kind: 'external',
        value: 'https://about.make.org/about-aines',
      },
      aboutUrl: 'https://about.make.org/about-aines',
      actions: null,
      featured: true,
      participantsCount: 0,
      proposalsCount: 0,
    },
    {
      questionId: 'c27b4109-68d8-4e12-91e2-eebb563f0ce8',
      questionSlug: 'vff',
      question: 'Stop aux violences faites aux femmes',
      shortTitle: null,
      operationTitle: 'Stop aux violences faites aux femmes',
      consultationImage: null,
      descriptionImage: null,
      country: 'FR',
      language: 'fr',
      startDate: '2018-03-08T00:00:00Z',
      endDate: '2020-06-08T23:00:00Z',
      theme: {
        gradientStart: '#000000',
        gradientEnd: '#000000',
        color: '#000000',
        fontColor: '#FFFFFF',
        secondaryColor: null,
        secondaryFontColor: null,
      },
      displayResults: false,
      resultsLink: null,
      aboutUrl: null,
      actions: null,
      featured: true,
      participantsCount: 0,
      proposalsCount: 0,
    },
    {
      questionId: '978542c4-4f0b-4382-b447-97f8c0d22fd8',
      questionSlug: 'test-question',
      question: 'test-questio',
      shortTitle: null,
      operationTitle: 'test',
      consultationImage: null,
      descriptionImage: null,
      country: 'FR',
      language: 'fr',
      startDate: '2019-05-15T00:00:00Z',
      endDate: '2019-05-31T00:00:00Z',
      theme: {
        gradientStart: '#000000',
        gradientEnd: '#000000',
        color: '#000000',
        fontColor: '#FFFFFF',
        secondaryColor: null,
        secondaryFontColor: null,
      },
      displayResults: false,
      resultsLink: null,
      aboutUrl: null,
      actions: null,
      featured: true,
      participantsCount: 0,
      proposalsCount: 0,
    },
  ],
  posts: [
    {
      title:
        'ÉVÉNEMENT : révélation des résultats de la consultation citoyenne #ActionEnvironnement',
      description:
        'Le 4 juin, lors d’une conférence virtuelle, des citoyens ayant participé à la consultation sur l’Environnement ont présenté leurs propositions, et plusieurs experts ont analysé les enseignements de cette consultation à la lumière de la crise actuelle.',
      picture:
        'https://uploads-ssl.webflow.com/5eddf33b5e82230118826e4b/5eddf33b5e8223a2a7827f1b_mosaique%20small.png',
      alt: null,
      link:
        'https://make-org-site-corpo-46934932a95d560c065.webflow.io/post/evenement-revelation-des-resultats-de-la-consultation-citoyenne-actionenvironnement',
    },
    {
      title:
        'ÉVÉNEMENT. Révélation des résultats de la consultation citoyenne “Inventons le monde d’après” ',
      description:
        'Le 28 mai, lors d’une conférence virtuelle, les partenaires d’“Inventons le monde d’après” et plusieurs citoyens ayant participé à la consultation ont présenté les 14 consensus identifiés, ainsi que les prochaines étapes de l’initiative.',
      picture:
        'https://uploads-ssl.webflow.com/5eddf33b5e82230118826e4b/5eddf33b5e822338b2827f0a_r%C3%A9sultats%20monde%20d%27apr%C3%A8s%20small.png',
      alt: null,
      link:
        'https://make-org-site-corpo-46934932a95d560c065.webflow.io/post/evenement-revelation-des-resultats-de-la-consultation-citoyenne-inventons-le-monde-dapres',
    },
    {
      title:
        '#MondeApres : la solidarité et l’entraide au cœur de la crise, et au-delà',
      description:
        'Chaque semaine, Make.org analyse un thème fréquemment cité par les participants à la consultation “Comment inventer tous ensemble le monde d’après ?”. (photo @unitednations/Unsplash )',
      picture:
        'https://uploads-ssl.webflow.com/5eddf33b5e82230118826e4b/5eddf33b5e82230840827ee9_solidarity%20small.png',
      alt: null,
      link:
        'https://make-org-site-corpo-46934932a95d560c065.webflow.io/post/mondeapres-la-solidarite-et-lentraide-au-coeur-de-la-crise-et-au-dela',
    },
  ],
};
