// @flow
export const CARD_TYPE_PROPOSAL = 'PROPOSAL_CARD';
export const CARD_TYPE_EXTRASLIDE_INTRO = 'EXTRASLIDE_INTRO_CARD';
export const CARD_TYPE_EXTRASLIDE_PUSH_PROPOSAL =
  'EXTRASLIDE_PUSH_PROPOSAL_CARD';
export const CARD_TYPE_EXTRASLIDE_PUSH_SIGNUP = 'EXTRASLIDE_PUSH_SIGNUP_CARD';
export const CARD_TYPE_EXTRASLIDE_FINAL_CARD = 'EXTRASLIDE_FINAL_CARD';

export const FEED_PROPOSAL = 'FEED_PROPOSAL';
export const FEED_TOP_PROPOSALS = 'FEED_TOP_PROPOSALS';

export const PROGRESS_SVG_VIEWBOX: string = '0 0 42 42';
export const PROGRESS_SVG_CX: number = 21;
export const PROGRESS_SVG_CY: number = 21;
export const PROGRESS_SVG_R: number = 15.91549430918954;
