// @flow
export const MODAL_LOGIN_CONTENT: string = 'MODAL_LOGIN_CONTENT';
export const MODAL_REGISTER_CONTENT: string = 'MODAL_REGISTER_CONTENT';
export const MODAL_FORGOT_PASSWORD_CONTENT: string =
  'MODAL_FORGOT_PASSWORD_CONTENT';
