// @flow

// Banner
export const ACTIVATION_SUCCESS_MESSAGE: string = 'ACTIVATION_SUCCESS_MESSAGE';
export const ACTIVATION_FAILURE_MESSAGE: string = 'ACTIVATION_FAILURE_MESSAGE';
export const ACCOUNT_DELETION_SUCCESS_MESSAGE: string =
  'ACCOUNT_DELETION_SUCCESS_MESSAGE';
export const PASSWORD_RECOVERY_FAILURE_MESSAGE: string =
  'PASSWORD_RECOVERY_FAILURE_MESSAGE';
export const LOGIN_SUCCESS_MESSAGE: string = 'LOGIN_SUCCESS_MESSAGE';
export const LOGOUT_SUCCESS_MESSAGE: string = 'LOGOUT_SUCCESS_MESSAGE';
export const REGISTER_SUCCESS_MESSAGE: string = 'REGISTER_SUCCESS_MESSAGE';
export const REGISTER_SUCCESS_VALIDATE_MESSAGE: string =
  'REGISTER_SUCCESS_VALIDATE_MESSAGE';
export const SECURE_EXPIRED_MESSAGE: string = 'SECURE_EXPIRED_MESSAGE';
export const UNEXPECTED_ERROR_MESSAGE: string = 'UNEXPECTED_ERROR_MESSAGE';
export const NETWORK_ERROR_MESSAGE: string = 'NETWORK_ERROR_MESSAGE';
export const VOTE_ONLY_MESSAGE: string = 'VOTE_ONLY_MESSAGE';

// Tip
export const TAGS_TIP_MESSAGE: string = 'TAGS_TIP_MESSAGE';
export const FIRST_VOTE_TIP_MESSAGE: string = 'FIRST_VOTE_TIP_MESSAGE';

export const NOTIFICATION_LEVEL_INFORMATION: string = 'information';
export const NOTIFICATION_LEVEL_SUCCESS: string = 'success';
export const NOTIFICATION_LEVEL_ERROR: string = 'error';
export const NOTIFICATION_LEVEL_ALERT: string = 'alert';
