/** Proposal Action */
export const PROPOSE_TYPING = 'PROPOSAL_PROPOSE_TYPING';
export const PROPOSE_REQUEST = 'PROPOSAL_PROPOSE_REQUEST';
export const PROPOSE_SUCCESS = 'PROPOSAL_PROPOSE_SUCCESS';
export const PROPOSE_FAILURE = 'PROPOSAL_PROPOSE_FAILURE';
/** Register Action */
export const REGISTER_REQUEST = 'USER_REGISTER_REQUEST';
export const REGISTER_SUCCESS = 'USER_REGISTER_SUCCESS';
export const REGISTER_FAILURE = 'USER_REGISTER_FAILURE';
/** Login Action */
export const LOGIN_REQUEST = 'USER_LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'USER_LOGIN_FAILURE';
export const GET_INFO = 'USER_GET_INFO';
export const LOGIN_SOCIAL_REQUEST = 'USER_LOGIN_SOCIAL_REQUEST';
export const LOGIN_SOCIAL_SUCCESS = 'USER_LOGIN_SOCIAL_SUCCESS';
export const LOGIN_SOCIAL_FAILURE = 'USER_LOGIN_SOCIAL_FAILURE';
export const LOGOUT = 'USER_LOGOUT';
/** Forgot Password Action */
export const FORGOT_PASSWORD_REQUEST = 'USER_FORGOT_PASSWORD_REQUEST';
export const FORGOT_PASSWORD_SUCCESS = 'USER_FORGOT_PASSWORD_SUCCESS';
export const FORGOT_PASSWORD_FAILURE = 'USER_FORGOT_PASSWORD_FAILURE';
export const FORGOT_PASSWORD_INIT = 'USER_FORGOT_PASSWORD_INIT';
/** Pannel action */
export const PANNEL_CLOSE = 'PANNEL_CLOSE';
export const PANNEL_SHOW_LOGIN = 'PANNEL_SHOW_LOGIN';
export const PANNEL_SHOW_REGISTER = 'PANNEL_SHOW_REGISTER';
export const PANNEL_SHOW_FORGOT_PASSWORD = 'PANNEL_SHOW_FORGOT_PASSWORD';
/** Sequence action */
export const SEQUENCE_COLLAPSE = 'SEQUENCE_COLLAPSE';
export const SEQUENCE_EXPAND = 'SEQUENCE_EXPAND';
